### PR TITLE
Update map.sh.new

### PR DESCRIPTION
**Pull request by angus19**
An enhancement to make use of full port ranges by leveraging meter + ct count rather than numgen.

### CODE REVIEW

**Comment by angus19** [comment]
With this change we could achieve similar action to what iptables does for **--connlimit-daddr** in connlimit extension.

**Comment by fakemanhk** [comment]
@cmspam What do you think?

**Comment by cmspam** [comment]
@fakemanhk I have given it a try, but I haven't found it using any ports outside of the first port range-- it is always getting matched on the first rule and doesn't use any of the subsequent rules. So I don't think it is successful. 

Only the first set of 25 ports, in my case, are being actually used, from what I can tell.

@angus19 Please correct me if I am wrong about this.

**Comment by cmspam** [comment]
An update... After further testing it turns out that the other port sets seem to be used properly. 

If there are not any issues, I think that this implementation is better than the previous one, so it should be merged.

**Comment by fakemanhk** [comment]
> An update... After further testing it turns out that the other port sets seem to be used properly.
> 
> If there are not any issues, I think that this implementation is better than the previous one, so it should be merged.

Cool, thanks for verification!

**Comment by cmspam** [comment]
@fakemanhk 
I have tested it, and with heavy use, it runs out of ports to use, it seems.
I don't know the exact reason.

I think it's better to revert to the old version pending further testing.

**Comment by fakemanhk** [comment]
> @fakemanhk I have tested it all day today, and unfortunately with heavy use, it runs out of ports to use, it seems. I don't know the exact reason.
> 
> I think it's better to revert to the old version pending further testing.

I have reverted to the previous version, but I would like to know how it compares to original one on the port usage.

**Comment by cmspam** [comment]
Unfortunately, I am not an expert with nftables, so my understanding of the way the map.sh in the PR works may be incorrect. @angus19 I would hope you can chime in on this, and maybe help with troubleshooting, because the idea you propose is nice in theory, but something is failing in practice.

The original version is rather simple: it builds a list of ports that can be used, taking into account a list of ports specified not to use, then creates a rule to cycle through the ports one by one to snat to. 

To my understanding, the version in this PR sets up one set for each port group. In my case they are set of 16 ports. It then creates one rule for each of these sets, with a limit of connections to a equal to the number or ports in a set (in my case 16 ports). I think the intent is when this limit is reached, the next set of ports is used, and so on.

Something about the way the rule is, causes the limit to be reached and a status of no more connections possible at a certain point, I think. It's also possible that it is not giving out unused ports, but rather giving out already-used ports for connections to the same IP/port in some circumstances, causing the connections to fail.

I think that it is important to have all of the functionality for a single protocol in one rule, instead of multiple rules. I remember when initially writing this script, I encountered similar problems that were fixed when I managed to make it all into one nft rule.

**Comment by angus19** [comment]
> @fakemanhk I have tested it all day today, and unfortunately with heavy use, it runs out of ports to use, it seems. I don't know the exact reason.
> 
> I think it's better to revert to the old version pending further testing.

@cmspam Possible share the mechanism/tool that stresses ports usage? Thanks.

**Comment by cmspam** [comment]
@angus19 
I am not using any specific tools to stress it. I am opening many TCP connections naturally and monitoring with regular linux tools such as conntrack, etc and checking which ports are being NATed to.

An easy way to open multiple TCP connections to a single host is using a multithreaded download manager like Axel to download a large file from the same host with multiple connections.

I haven't looked it this in a while, but having the multiple rules, in your implementation, it is always hitting one of the rules and following it and not the ones coming after.

**Comment by angus19** [comment]
@cmspam
Since you are mentioning TCP connections. I wonder if the following scenario is hit, although it happens to iptables. Guesses nftables has same outcome when leveraging connlimit.

- [MAP portsets not fully utilized and only 16 ports available due to discrepancies between connlimit and NAT?](https://forum.openwrt.org/t/map-portsets-not-fully-utilized-and-only-16-ports-available-due-to-discrepancies-between-connlimit-and-nat/105020)

**Comment by angus19** [comment]
Extra reference: [conntrack: TCP CLOSE and TIME_WAIT are not counted towards per-zone limit, and can overflow global table](https://lore.kernel.org/netdev/8c7e44d2-e78f-4f8d-9016-2a4b8429e14d@average.org/t/#u).

**Pull request merged**
